---
# This playbook is used to deploy generated unbound rules
- name: Verify pip dependencies
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - requests
  become: yes

- name: Generate unbound rules
  script: "{{ role_path }}/files/generate-unbound-rules.py"
  args:
    executable: /usr/bin/python3
  become: yes
  register: unbound_rules
  tags: unbound


- name: Deploy unbound rules on host
  copy:
    content: "{{ unbound_rules }}"
    dest: /etc/unbound/unbound.conf.d/youtube-ads-blocker.conf
  notify: restart unbound
  tags: unbound
